// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB859-gNM6-2C8hHSyEl2a1eZAQFCRoXwo',
    appId: '1:33330559301:web:e6de98a8f12fdda742a62c',
    messagingSenderId: '33330559301',
    projectId: 'simple-e-commerce-59773',
    authDomain: 'simple-e-commerce-59773.firebaseapp.com',
    storageBucket: 'simple-e-commerce-59773.firebasestorage.app',
    measurementId: 'G-NXV1FM3F6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwH7IShcDvKvFGC1LYwqs_aBEQ_5j0cU',
    appId: '1:33330559301:android:c52b62cd16705cca42a62c',
    messagingSenderId: '33330559301',
    projectId: 'simple-e-commerce-59773',
    storageBucket: 'simple-e-commerce-59773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENSsy5GY_RptFlNsxkFHNj9M3wc0wFHE',
    appId: '1:33330559301:ios:1cfd51f912b322c342a62c',
    messagingSenderId: '33330559301',
    projectId: 'simple-e-commerce-59773',
    storageBucket: 'simple-e-commerce-59773.firebasestorage.app',
    iosBundleId: 'com.example.simpleECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBENSsy5GY_RptFlNsxkFHNj9M3wc0wFHE',
    appId: '1:33330559301:ios:1cfd51f912b322c342a62c',
    messagingSenderId: '33330559301',
    projectId: 'simple-e-commerce-59773',
    storageBucket: 'simple-e-commerce-59773.firebasestorage.app',
    iosBundleId: 'com.example.simpleECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB859-gNM6-2C8hHSyEl2a1eZAQFCRoXwo',
    appId: '1:33330559301:web:36587cf4d5e87fda42a62c',
    messagingSenderId: '33330559301',
    projectId: 'simple-e-commerce-59773',
    authDomain: 'simple-e-commerce-59773.firebaseapp.com',
    storageBucket: 'simple-e-commerce-59773.firebasestorage.app',
    measurementId: 'G-D20MN3TQX1',
  );
}
